/**
 * Forgvi Engine — the Vube platform monorepo scaffold (spec pillars 1 + 2).
 *
 * The structure every web-app goal builds inside (the spec's directory
 * architecture, verbatim):
 *
 *   Forgeyn-workspace/
 *   ├── apps/
 *   │   ├── web-client/          Next.js IDE frontend — 18 pre-installed libs
 *   │   ├── api-server/          Core management API
 *   │   └── execution-engine/    Isolated code runner
 *   ├── packages/
 *   │   ├── vube-types/          Shared TypeScript definitions
 *   │   └── vube-ui/             Internal design system
 *   └── infrastructure/          Terraform / K8s / container configs
 *
 * Pillar 2: apps/web-client/package.json PRE-INSTALLS the mandated stack
 * (Tailwind, shadcn/ui, Motion, Magic UI, Aceternity, HeroUI, Lenis, GSAP,
 * React Three Fiber, Radix, Lucide, Sonner, Vaul, Embla, TanStack Query,
 * Zustand, React Hook Form, Zod) with working Tailwind + PostCSS + shadcn
 * config and a cn() utility, so the first `npm install` yields a
 * premium-UI-ready app and the agents never hand-roll infrastructure.
 */

/** The mandated stack (pillar 2 table, verbatim). */
export const VUBE_STACK = {
  "tailwindcss": "Styling engine",
  "shadcn-ui": "Core components (Radix-based, via components.json + src/lib)",
  "motion": "Core animation (physics-based micro-interactions)",
  "magic-ui": "Animated landing blocks (via registry deps)",
  "aceternity-ui": "Visual effects components (via registry deps)",
  "heroui": "Tailwind-native polished components",
  "lenis": "Inertia-based smooth scroll",
  "gsap": "Advanced scroll-driven animation",
  "three": "WebGL",
  "@react-three/fiber": "React Three Fiber 3D canvas",
  "@react-three/drei": "R3F helpers",
  "radix-ui": "Accessible unstyled primitives",
  "lucide-react": "Iconography",
  "sonner": "Toast notifications",
  "vaul": "Swipeable mobile drawers",
  "embla-carousel-react": "Physics carousel",
  "@tanstack/react-query": "Server state + optimistic UI",
  "zustand": "Client state store",
  "react-hook-form": "Uncontrolled form handling",
  "zod": "Schema validation",
  "clsx": "Class merge",
  "tailwind-merge": "Tailwind class merge",
  "class-variance-authority": "Variant components",
};

/** Versions for npm-installable members of the stack (permissive carets). */
const STACK_DEPS = {
  "tailwindcss": "^3.4.0",
  "postcss": "^8.4.0",
  "autoprefixer": "^10.4.0",
  "clsx": "^2.1.0",
  "tailwind-merge": "^2.5.0",
  "class-variance-authority": "^0.7.0",
  "motion": "^11.11.0",
  "lenis": "^1.1.0",
  "gsap": "^3.12.0",
  "three": "^0.169.0",
  "@react-three/fiber": "^8.17.0",
  "@react-three/drei": "^9.114.0",
  "@radix-ui/react-dialog": "^1.1.0",
  "@radix-ui/react-dropdown-menu": "^2.1.0",
  "@radix-ui/react-slot": "^1.1.0",
  "lucide-react": "^0.451.0",
  "sonner": "^1.7.0",
  "vaul": "^1.1.0",
  "embla-carousel-react": "^8.3.0",
  "@tanstack/react-query": "^5.59.0",
  "zustand": "^5.0.0",
  "react-hook-form": "^7.53.0",
  "zod": "^3.23.0",
  "@hookform/resolvers": "^3.9.0",
  "tailwindcss-animate": "^1.0.7",
};

/**
 * Build the full monorepo as {path, content} pairs (relative to the
 * workspace root). Pure data — the writer decides where it lands (VM or
 * local disk).
 */
export function buildVubeScaffold({ appName = "vube-app" } = {}) {
  const safeName = String(appName).replace(/[^a-z0-9-]/gi, "-").toLowerCase() || "vube-app";
  const files = [];
  const add = (path, content) => files.push({ path: String(path).replace(/^\/+/, ""), content: String(content) });

  // ── Root ────────────────────────────────────────────────────────────
  add(
    "package.json",
    JSON.stringify(
      {
        name: `${safeName}-workspace`,
        private: true,
        workspaces: ["apps/*", "packages/*"],
        scripts: {
          dev: "npm run dev --workspace apps/web-client",
          build: "npm run build --workspace apps/web-client",
          "dev:api": "npm run dev --workspace apps/api-server",
        },
        // HOISTING FIX (2026-09-04, live-observed on run c92327d2): Next.js's
        // webpack postcss-loader resolves plugins from the ROOT node_modules
        // of a monorepo (where `next` itself is hoisted), not the workspace's.
        // Without these root devDeps the production build dies with
        // "Cannot find module 'autoprefixer'" even though the web-client
        // declares them — the chief then burns its budget fighting npm.
        devDependencies: {
          postcss: "^8.4.0",
          autoprefixer: "^10.4.0",
          tailwindcss: "^3.4.0",
          "tailwindcss-animate": "^1.0.7",
        },
      },
      null,
      2,
    ),
  );
  add(
    "README.md",
    `# ${safeName}\n\nVube platform monorepo — generated by Forgevi 2.0.\n\n- \`apps/web-client\` — Next.js (App Router) frontend, the pre-installed premium UI stack\n- \`apps/api-server\` — core management API (auth, project tree, state persistence)\n- \`apps/execution-engine\` — isolated code runner (environments + in-container runner)\n- \`packages/vube-types\` — shared TypeScript definitions\n- \`packages/vube-ui\` — internal design system\n- \`infrastructure\` — deployment configs\n\nStart the frontend:\n\n    npm install\n    npm run dev\n`,
  );
  add(
    ".gitignore",
    ["node_modules/", ".next/", "dist/", ".env*.local", ".DS_Store", "*.log", ".turbo/", "coverage/"].join("\n"),
  );
  add(
    "tsconfig.base.json",
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          lib: ["dom", "dom.iterable", "esnext"],
          strict: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          esModuleInterop: true,
          skipLibCheck: true,
          jsx: "preserve",
          paths: { "@/*": ["./src/*"] },
        },
      },
      null,
      2,
    ),
  );

  // ── apps/web-client (pillar 2: the pre-installed stack) ─────────────
  add(
    "apps/web-client/package.json",
    JSON.stringify(
      {
        name: `${safeName}-web-client`,
        version: "0.1.0",
        private: true,
        scripts: {
          // PORT LAW: always -p. A bare `next dev 3000` is parsed by Next.js
          // as a DIRECTORY argument, not a port — the server dies with
          // "Couldn't find a directory 3000". Baked into the scaffold so
          // even a careless agent inherits the correct invocation.
          dev: "next dev -p 3000",
          build: "next build",
          start: "next start -p 3000",
          typecheck: "tsc --noEmit",
        },
        dependencies: {
          "react": "^18.3.0",
          "react-dom": "^18.3.0",
          "next": "^14.2.35",
          ...Object.fromEntries(
            Object.entries(STACK_DEPS).filter(([k]) => !["postcss", "autoprefixer"].includes(k)),
          ),
        },
        devDependencies: {
          postcss: STACK_DEPS.postcss,
          autoprefixer: STACK_DEPS.autoprefixer,
          "tailwindcss-animate": STACK_DEPS["tailwindcss-animate"],
          typescript: "^5.6.0",
          "@types/react": "^18.3.0",
          "@types/node": "^22.0.0",
        },
      },
      null,
      2,
    ),
  );
  add(
    "apps/web-client/next.config.mjs",
    `/** @type {import('next').NextConfig} */\nconst nextConfig = {\n  reactStrictMode: true,\n};\nexport default nextConfig;\n`,
  );
  add(
    "apps/web-client/postcss.config.mjs",
    `/** @type {import('postcss-load-config').Config} */\nconst config = {\n  plugins: { tailwindcss: {}, autoprefixer: {} },\n};\nexport default config;\n`,
  );
  add(
    "apps/web-client/tailwind.config.ts",
    `import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: ["./src/**/*.{ts,tsx,mdx}"],
  theme: {
    extend: {
      fontFamily: { sans: ["var(--font-sans)"] },
      colors: { border: "hsl(var(--border))" },
      keyframes: {
        "fade-up": { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        shimmer: { from: { backgroundPosition: "0 0" }, to: { backgroundPosition: "-200% 0" } },
      },
      animation: {
        "fade-up": "fade-up .5s ease both",
        shimmer: "shimmer 2s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
`,
  );
  add(
    "apps/web-client/tsconfig.json",
    JSON.stringify(
      {
        extends: "../../tsconfig.base.json",
        compilerOptions: {
          plugins: [{ name: "next" }],
          paths: { "@/*": ["./src/*"] },
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        exclude: ["node_modules"],
      },
      null,
      2,
    ),
  );
  add(
    "apps/web-client/components.json",
    JSON.stringify(
      {
        $schema: "https://ui.shadcn.com/schema.json",
        style: "default",
        rsc: true,
        tailwind: { config: "tailwind.config.ts", css: "src/app/globals.css", baseColor: "neutral", cssVariables: true },
        aliases: { components: "@/components", utils: "@/lib/utils", ui: "@/components/ui" },
      },
      null,
      2,
    ),
  );
  add(
    "apps/web-client/src/lib/utils.ts",
    `import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

/** Intelligent Tailwind class merge — no style conflicts. */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
`,
  );
  add(
    "apps/web-client/src/app/globals.css",
    `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 0 0% 9%;
    --border: 0 0% 90%;
  }
}

@layer utilities {
  .text-balance { text-wrap: balance; }
}
`,
  );
  add(
    "apps/web-client/src/app/layout.tsx",
    `"use client";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "sonner";
import { useEffect, useRef } from "react";
import Lenis from "lenis";
import "./globals.css";

/**
 * Root layout — the pre-installed stack's composition points:
 * TanStack Query provider, Sonner toasts, Lenis smooth scroll.
 */
export default function RootLayout({ children }: { children: React.ReactNode }) {
  const clientRef = useRef<QueryClient | null>(null);
  if (!clientRef.current) {
    clientRef.current = new QueryClient({
      defaultOptions: { queries: { staleTime: 30_000, refetchOnWindowFocus: false } },
    });
  }

  useEffect(() => {
    const lenis = new Lenis({ autoRaf: true });
    return () => lenis.destroy();
  }, []);

  return (
    <html lang="en">
      <body className="font-sans antialiased">
        <QueryClientProvider client={clientRef.current}>
          {children}
          <Toaster richColors position="bottom-right" />
        </QueryClientProvider>
      </body>
    </html>
  );
}
`,
  );
  add(
    "apps/web-client/src/app/page.tsx",
    `import { cn } from "@/lib/utils";

export default function HomePage() {
  return (
    <main className="min-h-screen bg-white text-neutral-950">
      <section className="mx-auto flex max-w-4xl flex-col items-center justify-center gap-6 px-6 py-32 text-center">
        <span className="rounded-full border border-neutral-200 px-3 py-1 text-xs text-neutral-500">
          Vube platform · pre-installed stack
        </span>
        <h1 className="text-balance text-4xl font-semibold tracking-tight md:text-6xl">
          ${safeName}
        </h1>
        <p className="max-w-xl text-balance text-neutral-500">
          Next.js + Tailwind + shadcn/ui + Motion + Lenis + TanStack Query + Zustand —
          build on top of this scaffold.
        </p>
      </section>
    </main>
  );
}
`,
  );
  add(
    "apps/web-client/src/lib/schemas.ts",
    `import { z } from "zod";

/** Zod-first domain validation (the stack's execution protocol). */
export const ProjectSchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(1).max(120),
  createdAt: z.string().datetime(),
});

export type Project = z.infer<typeof ProjectSchema>;
`,
  );

  // ── apps/api-server ────────────────────────────────────────────────
  add(
    "apps/api-server/package.json",
    JSON.stringify(
      {
        name: `${safeName}-api-server`,
        version: "0.1.0",
        private: true,
        type: "module",
        scripts: { dev: "node --watch src/index.ts", start: "node src/index.ts" },
        dependencies: { express: "^4.21.0", cors: "^2.8.5", zod: "^3.23.0" },
      },
      null,
      2,
    ),
  );
  add(
    "apps/api-server/src/index.ts",
    `import express from "express";
import { projectRoutes } from "./routes/projects.js";

const app = express();
app.use(express.json({ limit: "1mb" }));
app.use("/api/projects", projectRoutes);

app.get("/healthz", (_req, res) => res.json({ ok: true, service: "api-server" }));

const PORT = Number(process.env.PORT ?? 8787);
app.listen(PORT, () => console.log("api-server listening on :" + PORT));
`,
  );
  add(
    "apps/api-server/src/routes/projects.ts",
    `import { Router } from "express";
import { listProjects, createProject } from "../services/projects.js";

export const projectRoutes = Router();

projectRoutes.get("/", async (_req, res) => {
  res.json({ projects: await listProjects() });
});

projectRoutes.post("/", async (req, res) => {
  try {
    res.status(201).json(await createProject(req.body));
  } catch (error) {
    res.status(400).json({ error: { code: "invalid_project", message: String(error) } });
  }
});
`,
  );
  add(
    "apps/api-server/src/services/projects.ts",
    `/** Project persistence — swap the in-memory store for a real model layer. */
const store: Array<{ id: string; name: string; createdAt: string }> = [];

export async function listProjects() {
  return [...store];
}

export async function createProject(input: { name?: string }) {
  const name = String(input?.name ?? "").trim();
  if (!name) throw new Error("name is required");
  const row = { id: crypto.randomUUID(), name, createdAt: new Date().toISOString() };
  store.push(row);
  return row;
}
`,
  );

  // ── apps/execution-engine ──────────────────────────────────────────
  add(
    "apps/execution-engine/README.md",
    `# execution-engine\n\nIsolated code runner.\n\n- \`environments/\` — base Dockerfiles per language (node, python)\n- \`runner/\` — the lightweight in-container daemon (terminal piping + port forwarding)\n`,
  );
  add(
    "apps/execution-engine/environments/node.Dockerfile",
    `FROM node:22-slim\nWORKDIR /workspace\nRUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*\nUSER node\nCMD ["sleep", "infinity"]\n`,
  );
  add(
    "apps/execution-engine/environments/python.Dockerfile",
    `FROM python:3.12-slim\nWORKDIR /workspace\nRUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*\nCMD ["sleep", "infinity"]\n`,
  );
  add(
    "apps/execution-engine/runner/README.md",
    `# runner\n\nThe in-container daemon. Responsibilities:\n\n1. **Terminal piping** — stream stdin/stdout of PTY sessions out over the control socket.\n2. **Port forwarding** — expose container-local ports through the host tunnel.\n`,
  );

  // ── packages ───────────────────────────────────────────────────────
  add(
    "packages/vube-types/package.json",
    JSON.stringify(
      {
        name: "@vube/types",
        version: "0.1.0",
        private: true,
        type: "module",
        main: "src/index.ts",
        types: "src/index.ts",
      },
      null,
      2,
    ),
  );
  add(
    "packages/vube-types/src/index.ts",
    `/** Shared TypeScript definitions & schemas for the ${safeName} platform. */
import { z } from "zod";

export type AgentRole = "chief" | "frontend" | "backend" | "debugger";

export interface SandboxState {
  sandboxId: string;
  status: "provisioning" | "ready" | "busy" | "stopped";
  ports: Record<string, number>;
}

export const ProjectTreeSchema = z.object({
  projectId: z.string(),
  files: z.array(z.object({ path: z.string(), kind: z.enum(["file", "dir"]) })),
});
export type ProjectTree = z.infer<typeof ProjectTreeSchema>;
`,
  );
  add(
    "packages/vube-ui/package.json",
    JSON.stringify(
      {
        name: "@vube/ui",
        version: "0.1.0",
        private: true,
        type: "module",
        main: "src/index.ts",
        types: "src/index.ts",
        peerDependencies: { react: "^18.3.0", "lucide-react": "^0.451.0" },
      },
      null,
      2,
    ),
  );
  add(
    "packages/vube-ui/src/index.ts",
    `/** The internal design system — re-exports + primitives. */
export { cn } from "./utils.js";
`,
  );
  add(
    "packages/vube-ui/src/utils.ts",
    `import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
`,
  );

  // ── infrastructure ─────────────────────────────────────────────────
  add(
    "infrastructure/README.md",
    `# infrastructure\n\nDeployment configs (Terraform / Kubernetes / container). Placeholder —\nadd the platform's manifests here when the deployment surface lands.\n`,
  );
  add(
    "infrastructure/docker-compose.yml",
    `services:\n  web-client:\n    build: ../apps/web-client\n    ports: ["3000:3000"]\n  api-server:\n    build: ../apps/api-server\n    ports: ["8787:8787"]\n`,
  );

  return files;
}

/**
 * Write the scaffold into a workspace. Two backends:
 *   - VM-bound: vm.writeFile per file (the project sandbox's /workspace)
 *   - local: node fs (dev runs / engine-local fallback)
 * Returns {written, root, files}.
 */
export async function scaffoldVubeWorkspace(ctx = {}, { appName } = {}) {
  const files = buildVubeScaffold({ appName });
  if (ctx.vm) {
    // Batched parallel writes through the VM client (mkdir -p happens
    // inside writeFile's parent-dir step).
    const BATCH = 6;
    for (let i = 0; i < files.length; i += BATCH) {
      await Promise.all(files.slice(i, i + BATCH).map((f) => ctx.vm.client.writeFile(f.path, f.content)));
    }
    return { written: files.length, root: "/workspace", files: files.map((f) => f.path) };
  }
  if (ctx.localCwd) {
    const { mkdir, writeFile } = await import("node:fs/promises");
    const path = await import("node:path");
    for (const f of files) {
      const target = path.resolve(ctx.localCwd, f.path);
      await mkdir(path.resolve(target, ".."), { recursive: true });
      await writeFile(target, f.content, "utf-8");
    }
    return { written: files.length, root: ctx.localCwd, files: files.map((f) => f.path) };
  }
  return { ok: false, error: "scaffold: no workspace (neither VM nor local cwd) bound" };
}
